baseURL = "http://example.org/"
languageCode = "en-us"
title = "Made Raka"
theme = "whiteplain"
copyright = "&copy; Copyright 2017 Made Raka"

[[menu.main]]
  name = "Books"
  identifier = "books"
  url = "/books/"
  weight = 1

[[menu.main]]
  name = "About"
  identifier = "about"
  url = "/about/"
  weight = 2